/**
 * Static demo data for BloomOps when SHOW_DEMO_CONTENT=true and DB is empty.
 * Kept aligned with prisma/seed.ts catalog (names, SKUs, suppliers).
 *
 * Monthly figures cover May 2025 → Apr 2026 so the 12-month chart window
 * always looks populated regardless of when the demo is viewed.
 */

export function isDemoEnabled(): boolean {
  return process.env.SHOW_DEMO_CONTENT === "true";
}

// ─── Products ─────────────────────────────────────────────────────────────
export const DEMO_PRODUCTS = [
  {
    id: "demo-prod-1",
    name: "Red Roses",
    sku: "ROSE-RED-001",
    category: "flowers",
    unit: "bunch",
    costPrice: 8.5,
    sellPrice: 24.99,
    stockQty: 60,
    minStock: 15,
    isActive: true,
    supplier: { id: "demo-sup-1", name: "Dalmatia Flowers Supply" },
  },
  {
    id: "demo-prod-2",
    name: "White Tulips",
    sku: "TULIP-WHT-002",
    category: "flowers",
    unit: "bunch",
    costPrice: 4.5,
    sellPrice: 13.99,
    stockQty: 80,
    minStock: 20,
    isActive: true,
    supplier: { id: "demo-sup-1", name: "Dalmatia Flowers Supply" },
  },
  {
    id: "demo-prod-3",
    name: "Pink Peonies",
    sku: "PEON-PNK-003",
    category: "flowers",
    unit: "bunch",
    costPrice: 12.0,
    sellPrice: 34.99,
    stockQty: 28,
    minStock: 10,
    isActive: true,
    supplier: { id: "demo-sup-5", name: "Coastal Bloom Growers" },
  },
  {
    id: "demo-prod-4",
    name: "Eucalyptus Stems",
    sku: "EUCAL-004",
    category: "flowers",
    unit: "bunch",
    costPrice: 2.8,
    sellPrice: 8.99,
    stockQty: 120,
    minStock: 30,
    isActive: true,
    supplier: { id: "demo-sup-2", name: "Adriatic Floral Wholesale" },
  },
  {
    id: "demo-prod-5",
    name: "Mixed Seasonal Bouquet",
    sku: "BOUQ-SEA-005",
    category: "arrangements",
    unit: "each",
    costPrice: 15.0,
    sellPrice: 42.0,
    stockQty: 18,
    minStock: 5,
    isActive: true,
    supplier: { id: "demo-sup-2", name: "Adriatic Floral Wholesale" },
  },
  {
    id: "demo-prod-6",
    name: "White Carnations",
    sku: "CARN-WHT-006",
    category: "flowers",
    unit: "bunch",
    costPrice: 6.5,
    sellPrice: 18.99,
    stockQty: 72,
    minStock: 20,
    isActive: true,
    supplier: { id: "demo-sup-2", name: "Adriatic Floral Wholesale" },
  },
  {
    id: "demo-prod-7",
    name: "Satin Ribbon",
    sku: "RIB-SAT-007",
    category: "supplies",
    unit: "each",
    costPrice: 1.2,
    sellPrice: 3.99,
    stockQty: 200,
    minStock: 50,
    isActive: true,
    supplier: { id: "demo-sup-3", name: "Mediteran Packaging" },
  },
  {
    id: "demo-prod-8",
    name: "Kraft Wrapping Paper",
    sku: "WRAP-KFT-008",
    category: "supplies",
    unit: "each",
    costPrice: 0.3,
    sellPrice: 0.99,
    stockQty: 500,
    minStock: 100,
    isActive: true,
    supplier: { id: "demo-sup-3", name: "Mediteran Packaging" },
  },
  {
    id: "demo-prod-9",
    name: "Greeting Card",
    sku: "CARD-BLK-009",
    category: "supplies",
    unit: "each",
    costPrice: 0.5,
    sellPrice: 2.49,
    stockQty: 3,
    minStock: 20,
    isActive: true,
    supplier: { id: "demo-sup-3", name: "Mediteran Packaging" },
  },
  {
    id: "demo-prod-10",
    name: "Glass Vase",
    sku: "VASE-CLR-010",
    category: "supplies",
    unit: "each",
    costPrice: 3.5,
    sellPrice: 9.99,
    stockQty: 45,
    minStock: 15,
    isActive: true,
    supplier: { id: "demo-sup-4", name: "Flora Studio Partners" },
  },
  {
    id: "demo-prod-11",
    name: "Floral Foam Block",
    sku: "FOAM-BLK-011",
    category: "supplies",
    unit: "each",
    costPrice: 0.9,
    sellPrice: 2.99,
    stockQty: 150,
    minStock: 40,
    isActive: true,
    supplier: { id: "demo-sup-4", name: "Flora Studio Partners" },
  },
  {
    id: "demo-prod-12",
    name: "Succulent Arrangement (Small)",
    sku: "SUCC-MIX-012",
    category: "plants",
    unit: "each",
    costPrice: 12.0,
    sellPrice: 34.99,
    stockQty: 22,
    minStock: 8,
    isActive: true,
    supplier: { id: "demo-sup-6", name: "Sunrise Nursery Co." },
  },
];

// ─── Suppliers ────────────────────────────────────────────────────────────
export const DEMO_SUPPLIERS = [
  {
    id: "demo-sup-1",
    name: "Dalmatia Flowers Supply",
    contact: "Luka Horvat",
    email: "orders@dalmatiaflowers.hr",
    phone: "+385 21 555 0101",
    _count: { products: 2 },
  },
  {
    id: "demo-sup-2",
    name: "Adriatic Floral Wholesale",
    contact: "Maja Blažević",
    email: "wholesale@adriaticfloral.com",
    phone: "+385 51 555 0202",
    _count: { products: 4 },
  },
  {
    id: "demo-sup-3",
    name: "Mediteran Packaging",
    contact: "Ivan Perić",
    email: "sales@mediteranpkg.com",
    phone: "+385 1 555 0303",
    _count: { products: 3 },
  },
  {
    id: "demo-sup-4",
    name: "Flora Studio Partners",
    contact: "Ana Kovačević",
    email: "info@florastudiopartners.com",
    phone: "+385 20 555 0404",
    _count: { products: 2 },
  },
  {
    id: "demo-sup-5",
    name: "Coastal Bloom Growers",
    contact: "Tomislav Jurić",
    email: "contact@coastalbloom.hr",
    phone: "+385 23 555 0505",
    _count: { products: 1 },
  },
  {
    id: "demo-sup-6",
    name: "Sunrise Nursery Co.",
    contact: "Elena Matić",
    email: "hello@sunrisenursery.com",
    phone: "+385 31 555 0606",
    _count: { products: 1 },
  },
];

// ─── Shipments ────────────────────────────────────────────────────────────
export const DEMO_SHIPMENTS = [
  {
    id: "demo-ship-1",
    supplier: { name: "Dalmatia Flowers Supply" },
    status: "received",
    receivedAt: "2026-04-03",
    total: 1300.0,
  },
  {
    id: "demo-ship-2",
    supplier: { name: "Sunrise Nursery Co." },
    status: "received",
    receivedAt: "2026-03-06",
    total: 240.0,
  },
  {
    id: "demo-ship-3",
    supplier: { name: "Mediteran Packaging" },
    status: "received",
    receivedAt: "2026-02-04",
    total: 290.0,
  },
  {
    id: "demo-ship-4",
    supplier: { name: "Flora Studio Partners" },
    status: "pending",
    receivedAt: null,
    total: 120.0,
  },
  {
    id: "demo-ship-5",
    supplier: { name: "Coastal Bloom Growers" },
    status: "pending",
    receivedAt: null,
    total: 432.0,
  },
];

// ─── Orders ───────────────────────────────────────────────────────────────
export const DEMO_ORDERS = [
  {
    id: "demo-ord-1",
    orderNumber: "ORD-2025-042",
    status: "fulfilled",
    customerName: "Ana Kovač",
    deliveryDate: "2026-04-07",
    totalAmount: 62.47,
  },
  {
    id: "demo-ord-2",
    orderNumber: "ORD-2025-043",
    status: "fulfilled",
    customerName: "Nikola Babić",
    deliveryDate: "2026-04-09",
    totalAmount: 77.96,
  },
  {
    id: "demo-ord-3",
    orderNumber: "ORD-2025-044",
    status: "confirmed",
    customerName: "Marina Šimić",
    deliveryDate: "2026-04-10",
    totalAmount: 249.82,
  },
  {
    id: "demo-ord-4",
    orderNumber: "ORD-2025-045",
    status: "draft",
    customerName: "Petra Blažević",
    deliveryDate: "2026-04-19",
    totalAmount: 84.0,
  },
  {
    id: "demo-ord-5",
    orderNumber: "ORD-2025-046",
    status: "confirmed",
    customerName: "Office Bloom Ltd",
    deliveryDate: "2026-04-11",
    totalAmount: 101.92,
  },
  {
    id: "demo-ord-6",
    orderNumber: "ORD-2025-040",
    status: "fulfilled",
    customerName: "Karla Jurić",
    deliveryDate: "2026-03-27",
    totalAmount: 126.92,
  },
  {
    id: "demo-ord-7",
    orderNumber: "ORD-2025-039",
    status: "fulfilled",
    customerName: "Hotel Marjan",
    deliveryDate: "2026-03-22",
    totalAmount: 217.98,
  },
  {
    id: "demo-ord-8",
    orderNumber: "ORD-2025-037",
    status: "fulfilled",
    customerName: "Elena Matić",
    deliveryDate: "2026-03-08",
    totalAmount: 149.94,
  },
  {
    id: "demo-ord-9",
    orderNumber: "ORD-2025-035",
    status: "fulfilled",
    customerName: "Dario Horvat",
    deliveryDate: "2026-02-15",
    totalAmount: 149.91,
  },
  {
    id: "demo-ord-10",
    orderNumber: "ORD-2025-030",
    status: "fulfilled",
    customerName: "Ivana Tomić",
    deliveryDate: "2025-12-23",
    totalAmount: 393.86,
  },
];

// ─── Reports ──────────────────────────────────────────────────────────────
export const DEMO_REPORTS = {
  stockValueSummary: [
    { category: "flowers", totalUnits: 360, totalValue: 2380.5 },
    { category: "supplies", totalUnits: 898, totalValue: 892.2 },
    { category: "arrangements", totalUnits: 18, totalValue: 270.0 },
    { category: "plants", totalUnits: 22, totalValue: 264.0 },
  ],
  lowStockProducts: [
    {
      id: "demo-prod-9",
      name: "Greeting Card",
      sku: "CARD-BLK-009",
      category: "supplies",
      stockQty: 3,
      minStock: 20,
      supplierName: "Mediteran Packaging",
    },
  ],
  topSellingProducts: [
    { name: "Red Roses", sku: "ROSE-RED-001", totalQty: 156, totalRevenue: 3898.44 },
    { name: "Mixed Seasonal Bouquet", sku: "BOUQ-SEA-005", totalQty: 88, totalRevenue: 3696.0 },
    { name: "White Carnations", sku: "CARN-WHT-006", totalQty: 104, totalRevenue: 1974.96 },
    { name: "White Tulips", sku: "TULIP-WHT-002", totalQty: 98, totalRevenue: 1371.02 },
    { name: "Eucalyptus Stems", sku: "EUCAL-004", totalQty: 130, totalRevenue: 1168.70 },
    { name: "Succulent Arrangement (Small)", sku: "SUCC-MIX-012", totalQty: 38, totalRevenue: 1329.62 },
    { name: "Pink Peonies", sku: "PEON-PNK-003", totalQty: 42, totalRevenue: 1469.58 },
    { name: "Satin Ribbon", sku: "RIB-SAT-007", totalQty: 192, totalRevenue: 766.08 },
    { name: "Glass Vase", sku: "VASE-CLR-010", totalQty: 54, totalRevenue: 539.46 },
    { name: "Greeting Card", sku: "CARD-BLK-009", totalQty: 68, totalRevenue: 169.32 },
  ],
  monthlySalesTotals: [
    { month: "May 2025", totalSales: 980.0 },
    { month: "Jun 2025", totalSales: 1120.0 },
    { month: "Jul 2025", totalSales: 1290.0 },
    { month: "Aug 2025", totalSales: 1640.0 },
    { month: "Sep 2025", totalSales: 1510.0 },
    { month: "Oct 2025", totalSales: 2080.0 },
    { month: "Nov 2025", totalSales: 2340.0 },
    { month: "Dec 2025", totalSales: 2890.0 },
    { month: "Jan 2026", totalSales: 1180.0 },
    { month: "Feb 2026", totalSales: 2250.0 },
    { month: "Mar 2026", totalSales: 1870.0 },
    { month: "Apr 2026", totalSales: 1420.0 },
  ],
  monthlyGrossProfitTotals: [
    { month: "May 2025", grossProfit: 540.0 },
    { month: "Jun 2025", grossProfit: 615.0 },
    { month: "Jul 2025", grossProfit: 710.0 },
    { month: "Aug 2025", grossProfit: 900.0 },
    { month: "Sep 2025", grossProfit: 830.0 },
    { month: "Oct 2025", grossProfit: 1140.0 },
    { month: "Nov 2025", grossProfit: 1285.0 },
    { month: "Dec 2025", grossProfit: 1590.0 },
    { month: "Jan 2026", grossProfit: 650.0 },
    { month: "Feb 2026", grossProfit: 1235.0 },
    { month: "Mar 2026", grossProfit: 1030.0 },
    { month: "Apr 2026", grossProfit: 780.0 },
  ],
};

// ─── Dashboard KPIs & tables ──────────────────────────────────────────────
export const DEMO_DASHBOARD = {
  totalActiveProducts: 12,
  totalSuppliers: 6,
  lowStockCount: 1,
  totalStockUnits: 1298,
  estimatedStockValue: 6806.5,
  ordersThisMonth: 5,
  grossProfitThisMonth: 780.0,
  recentShipments: [
    {
      id: "demo-ship-1",
      supplierName: "Dalmatia Flowers Supply",
      status: "received",
      createdAt: new Date("2026-04-03"),
      total: 1300.0,
    },
    {
      id: "demo-ship-2",
      supplierName: "Sunrise Nursery Co.",
      status: "received",
      createdAt: new Date("2026-03-06"),
      total: 240.0,
    },
    {
      id: "demo-ship-4",
      supplierName: "Flora Studio Partners",
      status: "pending",
      createdAt: new Date("2026-04-08"),
      total: 120.0,
    },
  ],
  recentOrders: [
    {
      id: "demo-ord-5",
      orderNumber: "ORD-2025-046",
      status: "confirmed",
      customerName: "Office Bloom Ltd",
      totalAmount: 101.92,
      createdAt: new Date("2026-04-06"),
    },
    {
      id: "demo-ord-4",
      orderNumber: "ORD-2025-045",
      status: "draft",
      customerName: "Petra Blažević",
      totalAmount: 84.0,
      createdAt: new Date("2026-04-05"),
    },
    {
      id: "demo-ord-3",
      orderNumber: "ORD-2025-044",
      status: "confirmed",
      customerName: "Marina Šimić",
      totalAmount: 249.82,
      createdAt: new Date("2026-04-05"),
    },
    {
      id: "demo-ord-2",
      orderNumber: "ORD-2025-043",
      status: "fulfilled",
      customerName: "Nikola Babić",
      totalAmount: 77.96,
      createdAt: new Date("2026-04-04"),
    },
    {
      id: "demo-ord-1",
      orderNumber: "ORD-2025-042",
      status: "fulfilled",
      customerName: "Ana Kovač",
      totalAmount: 62.47,
      createdAt: new Date("2026-04-02"),
    },
  ],
  monthlyData: [
    { month: "May 2025", sales: 980, profit: 540 },
    { month: "Jun 2025", sales: 1120, profit: 615 },
    { month: "Jul 2025", sales: 1290, profit: 710 },
    { month: "Aug 2025", sales: 1640, profit: 900 },
    { month: "Sep 2025", sales: 1510, profit: 830 },
    { month: "Oct 2025", sales: 2080, profit: 1140 },
    { month: "Nov 2025", sales: 2340, profit: 1285 },
    { month: "Dec 2025", sales: 2890, profit: 1590 },
    { month: "Jan 2026", sales: 1180, profit: 650 },
    { month: "Feb 2026", sales: 2250, profit: 1235 },
    { month: "Mar 2026", sales: 1870, profit: 1030 },
    { month: "Apr 2026", sales: 1420, profit: 780 },
  ],
};
